# Generated by Django 3.1 on 2020-08-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0003_auto_20200818_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
